import { Injectable } from "@nestjs/common";
import { RelevanceTerm } from "@ebike-backend/database";
import { compact, uniqBy } from "lodash";

@Injectable()
export class RelevanceTermsService {
  /**
   * Term categories for diversity scoring.
   * Measures how many *types* of signals are present rather than raw term count.
   */
  public static readonly TERM_CATEGORIES: Record<string, string[]> = {
    intent: [
      "review",
      "reviews",
      "opinion",
      "opinions",
      "thoughts",
      "feedback",
      "worth it",
      "worth buying",
      "worth the money",
      "recommend",
      "recommendation",
      "compare",
      "compared to",
      "comparison",
      "vs",
      "versus",
    ],
    experience: [
      "i bought",
      "i purchased",
      "i tested",
      "i tried",
      "i use",
      "i used",
      "my experience",
      "my impressions",
      "first impressions",
      "hands on",
      "after using",
      "daily use",
      "months of use",
      "weeks of use",
      "out of the box",
      "just got",
      "got it today",
      "just received",
    ],
    sentiment: [
      "excellent",
      "love",
      "high quality",
      "works well",
      "perfect",
      "amazing",
      "satisfied",
      "pleased",
      "exceeded expectations",
      "gorgeous",
      "issue",
      "issues",
      "problem",
      "problems",
      "broken",
      "defective",
      "disappointed",
      "unsatisfied",
      "faulty",
    ],
    comparison: [
      "compared to",
      "better than",
      "worse than",
      "on par with",
      "coming from",
      "upgraded from",
      "previously had",
      "upgrade over",
      "worth the upgrade",
      "huge upgrade",
      "big upgrade",
    ],
    action: [
      "buy",
      "purchase",
      "upgrade",
      "return it",
      "returning",
      "recommend",
      "considering",
      "planning to buy",
      "looking to buy",
      "shopping for",
      "thinking of buying",
    ],
  };

  public getMergedTerms(
    baseTerms: RelevanceTerm[],
    additionalTerms?: RelevanceTerm[],
  ): RelevanceTerm[] {
    const extras = compact(additionalTerms ?? []);

    // Prioritize additional terms by ordering them first, then deduplicate by keyword.
    return uniqBy([...extras, ...baseTerms], (term) => term.keyword);
  }

  public getDefaultTerms(): RelevanceTerm[] {
    return [...RelevanceTermsService.defaultTerms];
  }

  private static readonly defaultTerms: RelevanceTerm[] = [
    // === Intent / Review Signals ===
    { keyword: "review", weight: 1.6 },
    { keyword: "reviews", weight: 1.6 },
    { keyword: "opinion", weight: 1.4 },
    { keyword: "opinions", weight: 1.4 },
    { keyword: "thoughts", weight: 1.3 },
    { keyword: "feedback", weight: 1.2 },
    { keyword: "worth it", weight: 1.5 },
    { keyword: "worth buying", weight: 1.5 },
    { keyword: "worth the money", weight: 1.4 },
    { keyword: "recommend", weight: 1.4 },
    { keyword: "recommendation", weight: 1.4 },
    { keyword: "compare", weight: 1.3 },
    { keyword: "compared to", weight: 1.3 },
    { keyword: "comparison", weight: 1.3 },
    { keyword: "vs", weight: 1.2 },
    { keyword: "versus", weight: 1.2 },
    { keyword: "alternative", weight: 1.2 },
    { keyword: "other choice", weight: 1.2 },
    { keyword: "cheaper", weight: 1.2 },
    { keyword: "more expensive", weight: 1.2 },
    { keyword: "highly recommend", weight: 1.6 },
    { keyword: "checked all my boxes", weight: 1.4 },

    // === First-Person / Experience ===
    { keyword: "i bought", weight: 1.4 },
    { keyword: "i've got", weight: 1.4 },
    { keyword: "just received", weight: 1.4 },
    { keyword: "received it", weight: 1.3 },
    { keyword: "the other day", weight: 1.2 },
    { keyword: "i own", weight: 1.2 },
    { keyword: "i purchased", weight: 1.4 },
    { keyword: "i tested", weight: 1.3 },
    { keyword: "i tried", weight: 1.3 },
    { keyword: "i use", weight: 1.2 },
    { keyword: "i used", weight: 1.2 },
    { keyword: "i recently got", weight: 1.3 },
    { keyword: "my experience", weight: 1.5 },
    { keyword: "my impressions", weight: 1.4 },
    { keyword: "hands on", weight: 1.4 },
    { keyword: "first impressions", weight: 1.5 },
    { keyword: "after using", weight: 1.3 },
    { keyword: "long term", weight: 1.2 },
    { keyword: "daily use", weight: 1.2 },
    { keyword: "real world usage", weight: 1.3 },
    { keyword: "months of use", weight: 1.3 },
    { keyword: "weeks of use", weight: 1.2 },
    { keyword: "after a week", weight: 1.2 },
    { keyword: "after a month", weight: 1.2 },
    { keyword: "out of the box", weight: 1.2 },
    { keyword: "on par with", weight: 1.2 },
    { keyword: "good for", weight: 1.2 },
    { keyword: "bad for", weight: 1.2 },
    { keyword: "i upgraded", weight: 1.2 },
    { keyword: "home use", weight: 1.2 },
    { keyword: "professional use", weight: 1.2 },
    { keyword: "gaming", weight: 1.2 },
    { keyword: "photography", weight: 1.2 },
    { keyword: "heavy use", weight: 1.2 },
    { keyword: "picked mine up", weight: 1.2 },
    { keyword: "currently testing", weight: 1.6 },
    { keyword: "similar experience", weight: 1.2 },
    { keyword: "enjoy the immersion", weight: 1.4 },

    // === Positive Sentiment ===
    { keyword: "excellent", weight: 1.5 },
    { keyword: "love", weight: 1.4 },
    { keyword: "high quality", weight: 1.5 },
    { keyword: "works well", weight: 1.3 },
    { keyword: "perfect", weight: 1.4 },
    { keyword: "gorgeous", weight: 1.4 },
    { keyword: "amazing", weight: 1.3 },
    { keyword: "satisfied", weight: 1.4 },
    { keyword: "pleased", weight: 1.3 },
    { keyword: "exceeded expectations", weight: 1.4 },
    { keyword: "met expectations", weight: 1.3 },

    // === Complaints / Problems ===
    { keyword: "issue", weight: 1.4 },
    { keyword: "issues", weight: 1.4 },
    { keyword: "problem", weight: 1.4 },
    { keyword: "problems", weight: 1.4 },
    { keyword: "not working", weight: 1.6 },
    { keyword: "doesn't work", weight: 1.6 },
    { keyword: "broken", weight: 1.4 },
    { keyword: "broke", weight: 1.4 },
    { keyword: "defective", weight: 1.5 },
    { keyword: "faulty", weight: 1.4 },
    { keyword: "returning", weight: 1.3 },
    { keyword: "return it", weight: 1.3 },
    { keyword: "should i return", weight: 1.4 },
    { keyword: "replacement", weight: 1.2 },
    { keyword: "warranty", weight: 1.1 },
    { keyword: "overheating", weight: 1.3 },
    { keyword: "crashing", weight: 1.4 },
    { keyword: "inconsistent", weight: 1.2 },
    { keyword: "mistake", weight: 1.2 },
    { keyword: "disappointed", weight: 1.4 },
    { keyword: "unsatisfied", weight: 1.4 },

    // === Purchase / Action ===
    { keyword: "buy", weight: 1.0 },
    { keyword: "purchase", weight: 1.0 },
    { keyword: "upgrade", weight: 1.0 },
    { keyword: "replace", weight: 1.0 },
    { keyword: "choose", weight: 0.9 },
    { keyword: "pick", weight: 0.9 },
    { keyword: "select", weight: 0.9 },
    { keyword: "considering", weight: 0.9 },
    { keyword: "thinking of buying", weight: 1.0 },
    { keyword: "looking to buy", weight: 1.0 },
    { keyword: "shopping for", weight: 1.0 },
    { keyword: "considering purchase", weight: 1.2 },
    { keyword: "planning to buy", weight: 1.2 },
    { keyword: "thinking about getting", weight: 1.1 },
    { keyword: "waiting for sale", weight: 1.0 },
    { keyword: "best option", weight: 0.9 },
    { keyword: "best choice", weight: 0.9 },

    // === Feature Evaluation / Expectations ===
    { keyword: "concerned about", weight: 1.3 },
    { keyword: "concern", weight: 1.2 },
    { keyword: "issue with", weight: 1.3 },
    { keyword: "potential issue", weight: 1.3 },
    { keyword: "might be", weight: 1.1 },
    { keyword: "could be", weight: 1.1 },
    { keyword: "expected to", weight: 1.2 },
    { keyword: "i'd expect", weight: 1.3 },
    { keyword: "works better", weight: 1.3 },
    { keyword: "should work", weight: 1.2 },
    { keyword: "better than", weight: 1.3 },
    { keyword: "worse than", weight: 1.3 },
    { keyword: "on paper", weight: 1.1 },

    // === Capability / Compatibility Evaluation (NEW) ===
    { keyword: "can i", weight: 1.4 },
    { keyword: "can you", weight: 1.3 },
    { keyword: "does it support", weight: 1.4 },
    { keyword: "works together", weight: 1.4 },
    { keyword: "at the same time", weight: 1.3 },
    { keyword: "enabled together", weight: 1.4 },
    { keyword: "limitations", weight: 1.3 },
    { keyword: "limited by", weight: 1.3 },
    { keyword: "bottleneck", weight: 1.3 },
    { keyword: "compatibility", weight: 1.4 },
    { keyword: "bandwidth", weight: 1.3 },

    // === Ownership / Satisfaction Validation (NEW) ===
    { keyword: "i have the", weight: 1.4 },
    { keyword: "i own the", weight: 1.4 },
    { keyword: "i use the", weight: 1.3 },
    { keyword: "i love my", weight: 1.4 },
    { keyword: "i absolutely love", weight: 1.5 },
    { keyword: "couldn't be happier", weight: 1.5 },
    { keyword: "no complaints", weight: 1.4 },
    { keyword: "no issues", weight: 1.4 },

    // === Upgrade / Comparison Context (NEW) ===
    { keyword: "coming from", weight: 1.4 },
    { keyword: "upgraded from", weight: 1.4 },
    { keyword: "previously had", weight: 1.3 },
    { keyword: "before this", weight: 1.2 },
    { keyword: "the upgrade", weight: 1.3 },
    { keyword: "worth the upgrade", weight: 1.4 },
    { keyword: "huge upgrade", weight: 1.5 },
    { keyword: "big upgrade", weight: 1.4 },
    { keyword: "upgrade over", weight: 1.4 },

    // === Review Meta Commentary (NEW) ===
    { keyword: "reviews don't mention", weight: 1.5 },
    { keyword: "rarely mentioned", weight: 1.4 },
    { keyword: "not talked about", weight: 1.4 },
    { keyword: "hidden issues", weight: 1.5 },

    // === ADDITIVE: Real-world Comment Signals (NEW, APPENDED ONLY) ===
    { keyword: "just got", weight: 1.4 },
    { keyword: "got it today", weight: 1.4 },
    { keyword: "being delivered", weight: 1.3 },
    { keyword: "arriving next", weight: 1.2 },
    { keyword: "did a ton of research", weight: 1.5 },
    { keyword: "price comparisons", weight: 1.4 },
    { keyword: "landed on", weight: 1.3 },
    { keyword: "leaning toward", weight: 1.3 },
    { keyword: "works without any problems", weight: 1.5 },
    { keyword: "unusable in my case", weight: 1.6 },
    { keyword: "black screen flicker", weight: 1.6 },
    { keyword: "losing a signal", weight: 1.5 },
    { keyword: "had to return", weight: 1.5 },
    { keyword: "can send a video", weight: 1.5 },
    { keyword: "recorded a video", weight: 1.4 },
    { keyword: "felt smoother", weight: 1.3 },
    { keyword: "colors are crazy", weight: 1.4 },
    { keyword: "curve feels just right", weight: 1.4 },
    { keyword: "too much curve", weight: 1.3 },
    { keyword: "feels distorted", weight: 1.3 },
    { keyword: "makes me nauseous", weight: 1.5 },
    { keyword: "after a couple days", weight: 1.2 },
    { keyword: "you dont notice it anymore", weight: 1.3 },
    { keyword: "so hyped", weight: 1.4 },
  ];
}
