import { Global, Module } from "@nestjs/common";
import { AppConfigService } from "./services/app-config.service";
import { AppSettingsConfigService } from "./sub-configs/app-settings.config.service";
import {
  PostgresConfigService,
  MongoConfigService,
  RedditConfigService,
  OpenAiConfigService,
  GeminiConfigService,
  ClaudeConfigService,
  OpenRouterConfigService,
  DeepSeekConfigService,
  DataForSeoConfigService,
  ExaConfigService,
  TaskConfigService,
  LoggerConfigService,
  ZyteConfigService,
  BunnyConfigService,
  CategoryConfigService,
  SourceConfigService,
} from "@ebike-backend/config";

@Global()
@Module({
  imports: [],
  providers: [
    AppConfigService,
    PostgresConfigService,
    MongoConfigService,
    AppSettingsConfigService,
    RedditConfigService,
    OpenAiConfigService,
    GeminiConfigService,
    ClaudeConfigService,
    OpenRouterConfigService,
    DeepSeekConfigService,
    DataForSeoConfigService,
    ExaConfigService,
    TaskConfigService,
    LoggerConfigService,
    ZyteConfigService,
    BunnyConfigService,
    CategoryConfigService,
    SourceConfigService,
  ],
  exports: [
    AppConfigService,
    PostgresConfigService,
    MongoConfigService,
    AppSettingsConfigService,
    RedditConfigService,
    OpenAiConfigService,
    GeminiConfigService,
    ClaudeConfigService,
    OpenRouterConfigService,
    DeepSeekConfigService,
    DataForSeoConfigService,
    ExaConfigService,
    TaskConfigService,
    LoggerConfigService,
    ZyteConfigService,
    BunnyConfigService,
    CategoryConfigService,
    SourceConfigService,
  ],
})
export class AppConfigModule {}
