import { Module } from '@nestjs/common';
import { PrometheusController } from './controllers';
import { PrometheusService } from './prometheus.service';
import { ThreadMetricsService } from './services/thread-metrics.service';
import {
  ProductMetricsService,
  RedditMetricsService,
  SchedulerMetricsService,
  ScrapeTaskMetricsService,
  TaskMetricsService,
  OpenAiMetricsService,
  AiMetricsService,
  PipelineMetricsService,
  ProductSearchMetricsService,
  PublicApiMetricsService,
  ThreadSearchMetricsService,
  IncrementalSyncMetricsService,
  ProductCollectionMetricsService,
  ZyteMetricsService,
  DuplicateDetectionMetricsService,
  TranslationMetricsService,
  ProductScrapingMetricsService,
} from './services';

@Module({
  imports: [],
  controllers: [PrometheusController],
  providers: [
    PrometheusService,
    RedditMetricsService,
    SchedulerMetricsService,
    TaskMetricsService,
    ThreadMetricsService,
    ScrapeTaskMetricsService,
    ProductMetricsService,
    AiMetricsService,
    OpenAiMetricsService,
    PipelineMetricsService,
    ProductSearchMetricsService,
    PublicApiMetricsService,
    ThreadSearchMetricsService,
    IncrementalSyncMetricsService,
    ProductCollectionMetricsService,
    ZyteMetricsService,
    DuplicateDetectionMetricsService,
    TranslationMetricsService,
    ProductScrapingMetricsService,
  ],
  exports: [
    RedditMetricsService,
    SchedulerMetricsService,
    TaskMetricsService,
    ThreadMetricsService,
    ScrapeTaskMetricsService,
    ProductMetricsService,
    AiMetricsService,
    OpenAiMetricsService,
    PipelineMetricsService,
    ProductSearchMetricsService,
    PublicApiMetricsService,
    ThreadSearchMetricsService,
    IncrementalSyncMetricsService,
    ProductCollectionMetricsService,
    ZyteMetricsService,
    DuplicateDetectionMetricsService,
    TranslationMetricsService,
    ProductScrapingMetricsService,
  ],
})
export class MetricsModule {}
