services:
  # mongo:
  #   image: mongo
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: root
  #   volumes:
  #     - '~/mongodata:/data/db'
  #   ports:
  #     - 27017:27017
  #   networks:
  #     - backend

  postgres:
    container_name: ebike_postgres
    image: ankane/pgvector:latest
    environment:
      POSTGRES_USER: ebike
      POSTGRES_PASSWORD: ebike
      POSTGRES_DB: ebike
      PGDATA: /data/postgres
    volumes:
      - "E://Work/ebike/docker_data/ebike_postgres:/data/postgres"
    ports:
      - "5432:5432"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3101:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin # default user
      - GF_SECURITY_ADMIN_PASSWORD=J8v!s7QpLz#2wXrT
    volumes:
      - E://Work/ebike/docker_data/ebike_grafana:/var/lib/grafana
    depends_on:
      - loki
    networks:
      - backend

  loki:
    image: grafana/loki:3.6.2
    ports:
      - "3100:3100"
    volumes:
      - E://Work/ebike/docker_data/ebike_loki:/data
      - ./loki-config.yml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - backend

  prometheus:
    image: prom/prometheus:latest
    container_name: ebike_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./pipeline_alerts.yml:/etc/prometheus/pipeline_alerts.yml:ro
      - E://Work/ebike/docker_data/ebike_prometheus:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
    depends_on:
      - loki
    networks:
      - backend

networks:
  backend:
    driver: bridge
