import { Global, Module } from "@nestjs/common";
import { AppConfigService } from "./services/app-config.service";
import { AppSettingsConfigService } from "./sub-configs/app-settings.config.service";
import {
  PostgresConfigService,
  MongoConfigService,
  RedditConfigService,
  OpenAiConfigService,
  GeminiConfigService,
  ClaudeConfigService,
  OpenRouterConfigService,
  DeepSeekConfigService,
  DataForSeoConfigService,
  TaskConfigService,
  LoggerConfigService,
  ZyteConfigService,
  SupabaseConfigService,
  BunnyConfigService,
  CategoryConfigService,
  SourceConfigService,
  ProcessorConfigService,
} from "@ebike-backend/config";
import { DynamicConfigModule } from "@ebike-backend/dynamic-config";

@Global()
@Module({
  imports: [DynamicConfigModule],
  providers: [
    AppConfigService,
    PostgresConfigService,
    MongoConfigService,
    AppSettingsConfigService,
    RedditConfigService,
    OpenAiConfigService,
    GeminiConfigService,
    ClaudeConfigService,
    OpenRouterConfigService,
    DeepSeekConfigService,
    DataForSeoConfigService,
    TaskConfigService,
    LoggerConfigService,
    ZyteConfigService,
    SupabaseConfigService,
    BunnyConfigService,
    CategoryConfigService,
    SourceConfigService,
    ProcessorConfigService,
  ],
  exports: [
    AppConfigService,
    PostgresConfigService,
    MongoConfigService,
    AppSettingsConfigService,
    RedditConfigService,
    OpenAiConfigService,
    GeminiConfigService,
    ClaudeConfigService,
    OpenRouterConfigService,
    DeepSeekConfigService,
    DataForSeoConfigService,
    TaskConfigService,
    LoggerConfigService,
    ZyteConfigService,
    SupabaseConfigService,
    BunnyConfigService,
    CategoryConfigService,
    SourceConfigService,
    ProcessorConfigService,
  ],
})
export class AppConfigModule {}
