{
 "title": "Review Collector metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Scheduler Started",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(scheduler_started_total{app=\"ebike-review-collector\"}[$__interval])",
     "legendFormat": "{{app}} / {{scheduler_name}}"
    }
   ]
  },
  {
   "title": "Scheduler Finished",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "increase(scheduler_finished_total{app=\"ebike-review-collector\"}[$__interval])",
     "legendFormat": "{{app}} / {{scheduler_name}}"
    }
   ]
  },
  {
   "title": "Scheduler Failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "increase(scheduler_failed_total{app=\"ebike-review-collector\"}[$__interval])",
     "legendFormat": "{{app}} / {{scheduler_name}}"
    }
   ]
  },
  {
   "title": "Total HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "http_requests_total{app=\"ebike-review-collector\"}",
     "legendFormat": "{{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_sum{app=\"ebike-review-collector\"} / http_request_duration_seconds_count{app=\"ebike-review-collector\"}",
     "legendFormat": "Average Request Duration"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{app=\"ebike-review-collector\"}",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{app=\"ebike-review-collector\"}[1m])",
     "legendFormat": "CPU Usage"
    }
   ]
  }
 ]
}